export const path = {
  '*': '*',
  '/*': '/*',
  base: '/',
  cards: '/cards',
  checkEmail: '/check-email',
  createNewPassword: '/create-new-password',
  decks: '/decks',
  learn: '/learn',
  login: '/login',
  notFound: '/404',
  profile: '/profile',
  recoverPassword: '/recover-password',
  signUp: '/signUp',
} as const
